// Login
export const RETRIEVED_LOGIN_STATUS = "RETRIEVED_LOGIN_STATUS";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const DO_LOGIN_ATTEMPT = "DO_LOGIN_ATTEMPT";
export const DO_LOGOUT = "DO_LOGOUT";
// Items
export const DO_FETCH_ITEMS = "DO_FETCH_ITEMS";
export const FETCHED_ITEMS = "FETCHED_ITEMS";
// Invite
export const RETRIEVED_INVITE_STATUS = "RETRIEVED_INVITE_STATUS";
export const INVITE_LOADING = "INVITE_LOADING";
export const DO_INVITE_SEND = "DO_INVITE_SEND";
export const RETRIEVED_INVITE_CONFIRM_STATUS = "RETRIEVED_INVITE_CONFIRM_STATUS";
export const DO_INVITE_CONFIRM = "DO_INVITE_CONFIRM";
