// Login
export const RETRIEVED_LOGIN_STATUS = "RETRIEVED_LOGIN_STATUS";
export const DO_LOGIN_ATTEMPT = "DO_LOGIN_ATTEMPT";
export const DO_LOGOUT = "DO_LOGOUT";
export const DO_RESET_PASSWORD_REQUEST = "DO_RESET_PASSWORD_REQUEST";
export const DO_RESET_PASSWORD_ATTEMPT = "DO_RESET_PASSWORD_ATTEMPT";
export const RETRIEVED_RESET_PASSWORD_STATUS = "RETRIEVED_RESET_PASSWORD_STATUS";
// Items
export const DO_FETCH_ITEMS = "DO_FETCH_ITEMS";
export const FETCHED_ITEMS = "FETCHED_ITEMS";
export const DO_FETCH_ITEM_STAT = "DO_FETCH_ITEM_STAT";
export const FETCHED_ITEM_STAT = "FETCHED_ITEM_STAT";
// Invite
export const RETRIEVED_INVITE_STATUS = "RETRIEVED_INVITE_STATUS";
export const DO_INVITE_SEND = "DO_INVITE_SEND";
export const RETRIEVED_INVITE_CONFIRM_STATUS = "RETRIEVED_INVITE_CONFIRM_STATUS";
export const DO_INVITE_CONFIRM = "DO_INVITE_CONFIRM";
// APIKey
export const DO_CREATE_API_KEY_ATTEMPT = "DO_CREATE_API_KEY_ATTEMPT";
export const RETRIEVED_CREATE_API_KEY_STATUS = "RETRIEVED_CREATE_API_KEY_STATUS";
// Loading
export const PAGE_LOADING = "PAGE_LOADING";
